# Generated by Django 3.2.8 on 2021-10-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('weather', models.CharField(choices=[('SU', 'Sunny'), ('RA', 'Raining')], max_length=2)),
                ('address', models.CharField(max_length=156)),
                ('description', models.TextField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
