# Generated by Django 3.2.8 on 2021-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='address',
        ),
        migrations.AddField(
            model_name='activity',
            name='address1',
            field=models.CharField(default='null', max_length=1024, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='address2',
            field=models.CharField(default='null', max_length=1024, verbose_name='Address line 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(default='null', max_length=1024, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='zip_code',
            field=models.CharField(default='4560', max_length=12, verbose_name='ZIP / Postal code'),
            preserve_default=False,
        ),
    ]
