# Generated by Django 3.2.8 on 2021-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_auto_20211025_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('weather', models.CharField(choices=[('SU', 'Sunny'), ('RA', 'Raining')], max_length=2)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('description', models.TextField(max_length=1024)),
                ('cost', models.CharField(choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], max_length=2)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
