# Generated by Django 3.2.8 on 2021-10-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20211025_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='time_scene',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], default='BR', max_length=2),
            preserve_default=False,
        ),
    ]
