# Generated by Django 3.2.8 on 2021-10-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='genre',
            field=models.CharField(choices=[('AC', 'Activity'), ('FO', 'Food')], default='AC', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='genre',
            field=models.CharField(choices=[('AC', 'Activity'), ('FO', 'Food')], default='FO', max_length=2),
            preserve_default=False,
        ),
    ]
