# Generated by Django 3.2.8 on 2021-11-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_auto_20211026_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Resturant',
        ),
    ]
